### ISSUE TITLE
Contributing preparation with py.test

### ISSUE THREAD

**Issue by Semo** [joowani/kq#18]
I wanted to contribute some code. 
`py.test --cov=kq --cov-report=html ` did not work for me. Is there something I missed? Command not found. It's my first try. All previous steps described worked fine.

**Comment by joowani** [comment]
Hi @Semo,

Have you followed all the steps here? https://github.com/joowani/kq/blob/main/CONTRIBUTING.md
The `pip install -e .[dev]` should install all the dependencies for development, including pytest.
If you're using virtual env, I'd recommend you double check that as well.

**Comment by Semo** [comment]
I did. (Hopefully)

0. `git clone` and cd'ing into it.  OK
1. `python3 -m venv kq_dev`    OK
2. `source ./kq_dev/bin/activate `  OK
3. `pip install -e .`  OK
4. `pip install pre-commit`    OK
5. `podman run -d -p 9092:9092 -e ADV_HOST=127.0.0.1 lensesio/fast-data-dev`    OK
6. `py.test --cov=kq --cov-report=html`    FAILS

In step 3 `pip install -e .[dev]` --> `no matches found: .[dev]`, therefore I left it empty.

**Comment by joowani** [comment]
Did you run `pip install -e .[dev]` in the kq repository folder? You can just manually install pytest by running the following in your venv:

```
pip install pytest pytest-cov
```

**Comment by Semo** [comment]
Yes I ran it in the kq repo folder, which is made, when cloned from Github, where Contibuting.md and README.md and stuff is residing.

I'll use the command you gave me. 

EDIT: The manual command worked fine. Thank you.
